accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.radius_login, name='radius_login'),
    path('register/', views.radius_register, name='radius_register'),
    path('logout/', views.radius_logout, name='radius_logout'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView

admin.AdminSite.site_title = settings.ADMIN_SITE_TITLE
admin.AdminSite.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base.html')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('sso/', include('radius.urls', namespace='radius'))
    
]

accounts/models.py
from django.db import models

    
class RadiusUser(models.Model):
    JENIS_KELAMIN = [
        ('', '--Pilih Jenis Kelamin--'),
        ('Pria', 'Pria'),
        ('Wanita', 'Wanita'),
    ]
    
    JENIS_USER = [
        ('MAHASISWA', 'MAHASISWA'),
        ('POLTEKBA', 'POLTEKBA'),
    ]
    
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=128)
    email = models.CharField(max_length=64, null=True, blank=True)
    nama_lengkap = models.CharField(max_length=128, null=True, blank=True)
    nik_or_nim = models.CharField(max_length=64, null=True, blank=True)
    jenis_user = models.CharField(
        max_length=32,
        choices=JENIS_USER,
        default='MAHASISWA',
        null=True,
        blank=True
    )
    no_hp = models.CharField(
        max_length=32,
        null=True,
        blank=True
        )
    jenis_kelamin = models.CharField(
        max_length=32,
        choices=JENIS_KELAMIN,
        null=True,
        blank=True
        )
    jurusan = models.CharField(
        max_length=100,
        null=True,
        blank=True
        )
    semester = models.CharField(
        max_length=48,
        null=True,
        blank=True,
        )
    active_user = models.BooleanField(default=True)
    alamat = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.username
    
    def set_password(self, raw_password):
        from accounts.backends import create_password
        self.radius_password = create_password(raw_password)
        
    def check_password(self, raw_password):
        from accounts.backends import cek_password
        return cek_password(raw_password, self.radius_password)
    
    @property
    def is_active(self):
        return self.active_user == True
    
    @property
    def is_authenticated(self) -> bool:
        return True
    
    @property
    def is_anonymous(self) -> bool:
        return False
    

accounts/forms.py
from django import forms
from .models import RadiusUser


class RadiusUserRegisterForm(forms.ModelForm):
    class Meta:
        model = RadiusUser
        fields = (
            'username',
            'password',
            'email',
            'nama_lengkap',
            'nik_or_nim',
            'no_hp',
            'jenis_kelamin',
            'jurusan',
            'semester',
            'alamat',
        )

accounts/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.conf import settings
from .models import RadiusUser
from .forms import RadiusUserRegisterForm
from .backends import create_password


def radius_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'Login Berhasil!')
                    return redirect(settings.LOGIN_REDIRECT_URL)
                else:
                    context = {'message': 'Username atau password salah!'}
                    return render(request, 'accounts/login.html', context)
                
        if request.method == 'GET':
            return render(request, 'accounts/login.html', {})
    return redirect(settings.LOGIN_REDIRECT_URL)
    
    
def radius_register(request):
    if request.method == 'POST':
        form = RadiusUserRegisterForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            password = form.cleaned_data['password']
            form.password = create_password(password) # type: ignore
            form.save(commit=True)
            messages.success(request, 'Registrasi Berhasil, silahkan login dengan username & password anda.')
            return HttpResponseRedirect(settings.LOGIN_URL)
        
        context = {
            'message': 'Registrasi gagal, mohon periksa kembali data anda.',
            'form': RadiusUserRegisterForm()
            }
        return render(request, 'accounts/registrasi.html', context)
    
    return render(request, 'accounts/registrasi.html', {'form': RadiusUserRegisterForm()})


def radius_logout(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Done, Anda telah logout!")
        return redirect('accounts:login')
    messages.error(request, 'Anda belum login.')
    return redirect(settings.LOGIN_URL)

templates/accounts/login.html
{% extends "auth_base.html" %} {% block content %} {% load static %}
<div class="row">
  <div class="col-lg-8 col-12 banner-sec">
    <div id="carouselIndicator" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselIndicator" data-slide-to="0"></li>
      </ol>
      <div class="carousel-inner" role="list-box">
        <div class="carousel-item active">
          <img
            class="d-block img-fluid"
            src="{% static '/assets/dist/img/carousel/sso-image1.png' %}"
            alt="First slide"
          />
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-12 login-sec">
    <div class="text-center mb-2">
      <img src="{% static '/assets/dist/img/sso-logo.png' %}" width="30%" />
    </div>
    <form action="" id="form-login" method="post">
      {% csrf_token %}
      <h2 class="text-center">Login</h2>
      <div class="form-group">
        <input
          type="text"
          name="username"
          id="username-login"
          class="form-control"
          placeholder="NIM / Username"
        />
      </div>
      <div class="form-group">
        <input
          type="password"
          name="password"
          id="password-login"
          class="form-control"
          placeholder="Password"
        />
      </div>
      <div>
        <label for="" class="form-check-label"
          ><small><a href="#">Lupa Password?</a></small></label
        >
        <div class="float-right" style="padding-left: 0px; margin-top: -5px">
          <button type="submit" class="btn btn-login">Login</button>
        </div>
      </div>
      <hr />
      <div style="text-align: center" class="mb-3">
        <small
          >Tidak punya akun ?
          <a href="{% url 'accounts:radius_register' %}" class="tab-register"
            >Daftar Disini</a
          ></small
        >
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/accounts/registrasi.html
{% extends "auth_base.html" %} {% block content %} {% load static %}
<div class="row">
  <div class="col-lg-8 col-12 banner-sec">
    <div id="carouselIndicator" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselIndicator" data-slide-to="0"></li>
      </ol>
      <div class="carousel-inner" role="list-box">
        <div class="carousel-item active">
          <img
            class="d-block img-fluid"
            src="{% static '/assets/dist/img/carousel/sso-image1.png' %}"
            alt="First slide"
          />
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-12 login-sec">
    <div class="text-center mb-2">
      <img src="{% static '/assets/dist/img/sso-logo.png' %}" width="30%" />
    </div>
    <form action="" id="form-login" method="post">
      {% csrf_token %}
      <h2 class="text-center">Registrasi</h2>
      <div class="form-group">
        <input
          type="text"
          name="username"
          id="username"
          class="form-control"
          placeholder="NIM / Username"
          required
        />
      </div>
      <div class="row">
        <div class="col-12">
          <div class="form-group">
            <div class="input-group">
              <input
                type="text"
                name="nama_lengkap"
                id="nama_lengkap"
                class="form-control"
                placeholder="Nama Lengkap"
              />
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <div class="input-group">
              <input
                type="password"
                name="password"
                id="password"
                class="form-control"
                placeholder="Password"
              />
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <div class="input-group">
              <input
                type="password"
                name="password_confirm"
                id="password_confirm"
                class="form-control"
                placeholder="Ulangi Password"
              />
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <select
              name="jenis_kelamin"
              id="jenis_kelamin"
              class="form-control"
            >
              <option value="">Laki-laki</option>
              <option value="">Perempuan</option>
            </select>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <div class="input-group">
              <input
                type="text"
                name="no_hp"
                id="no_hp"
                class="form-control"
                placeholder="No HP"
              />
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="form-select">
            <div class="input-group">
              <input
                type="text"
                name="jurusan"
                id="jurusan"
                class="form-control"
                placeholder="Jurusan"
              />
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <div class="input-group">
              <input
                type="text"
                name="semester"
                id="semester"
                class="form-control"
                placeholder="Semester"
              />
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-8" style="padding-right: 5px">
            <button
              type="submit"
              id="register-submit-btn"
              class="btn btn-login btn-block"
            >
              Daftar
              <span
                class="spinner-border spinner-border-sm d-none"
                id="register-spinner"
                role="status"
                aria-hidden="true"
              >
                <span class="sr-only">Loading...</span>
              </span>
            </button>
          </div>
          <div class="col-4" style="padding-left: 5px">
            <span
              class="btn btn-warning btn-block"
              onclick="resetFormRegister()"
              >Reset</span
            >
          </div>
        </div>
      </div>
      <hr />
      <div style="text-align: center" class="mb-3">
        <small
          >Sudah punya akun ?
          <a href="{% url 'accounts:radius_login' %}" class="tab-register"
            >Login</a
          ></small
        >
      </div>
    </form>
  </div>
</div>

<script>
  function resetFormRegister() {
    $("#username").val("");
    $("#nama_lengkap").val("");
    $("#password").val("");
    $("#password_confirm").val("");
    $("#no_hp").val("");
    $("#jurusan").val("");
    $("#semester").val("");
  }

  function showPassword() {
    getType1 = document.getElementById("password");
    getType2 = document.getElementById("password_confirm");

    if (getType1.type === "password") {
      getType1.type = "text";
    } else {
      getType1.type = "password";
    }
    if (getType2.type === "password") {
      getType2.type = "text";
    } else {
      getType2.type = "password";
    }
  }
</script>
{% endblock content %}