base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView

admin.AdminSite.site_title = settings.ADMIN_SITE_TITLE
admin.AdminSite.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base.html')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('sso/', include('radius.urls', namespace='radius'))
    
]

radius/urls.py
from django.urls import path
from .views import AccountingView, PostAuthView

app_name = 'radius'

urlpatterns = [
    path('usages', AccountingView.as_view(), name='usages-view'),
    path('log-auth', PostAuthView.as_view(), name='log-auth-view')
]

templates/auth_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Masuk{% endblock title %} - SSO Poltekba</title>

    <!-- Google Font: Source Sans Pro -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="{% static '/assets/plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- icheck bootstrap -->
    <link
      rel="stylesheet"
      href="{% static '/assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}"
    />
    <!-- Theme style -->
    <link
      rel="stylesheet"
      href="{% static '/assets/dist/css/adminlte.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static '/assets/dist/css/optional.css' %}"
    />
  </head>
  <body>
    <div class="container">{% block content %}{% endblock content %}</div>
    <!-- /.login-box -->

    <!-- jQuery -->
    <script src="{% static '/assets/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static '/assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static '/assets/dist/js/adminlte.min.js' %}"></script>
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> {% block title %}Dashboard{% endblock title %} | SSO Poltekba</title>  
  <link rel="shortcut icon" href="{% static '/assets/dist/img/book.png' %}">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static '/assets/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{% static '/assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/assets/loading/load.css' %}"> 
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static '/assets/dist/css/adminlte.min.css' %}"> 
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" onclick="darkMode()" role="button"><i class="fas fa-moon"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-primary" data-toggle="dropdown" href="#">
          <i class="img-circle elevation-2 far fa-user mr-1" alt="User Avatar"></i>
          Admin
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Profile
              </a>
            <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Activities
              </a>

            <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Settings
              </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item has-icon">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a> 
        </div>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="" class="brand-link" class="bg-danger">
      <img src="{% static '/assets/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">SSO POLTEKBA</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar User -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex justify-content-center">
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      {% include 'sidebar.html' %}
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{% block pagetitle %}Dashboard{% endblock pagetitle %}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              {% comment %} <li class="breadcrumb-item active">Starter Page</li> {% endcomment %}
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <div class="content">
        <div class="container-fluid">
          {% block content %}{% endblock content %}
        </div>
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>&copy; <span id="year"></span> 
    </strong>
    UPTSI Politeknik Negeri Balikpapan
    <div class="float-right d-none d-sm-inline-block">
      v0.1.0-dev
    </div>
</footer>

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static '/assets/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static '/assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script> 
<!-- AdminLTE App -->
<script src="{% static '/assets/dist/js/adminlte.min.js' %}"></script> 

<script type="text/javascript">
  // footer year
  document.getElementById("year").innerHTML = new Date().getFullYear();

  // enable dark mode
  function darkMode(){
    const bodyDark = document.body.classList.contains('dark-mode');
    if (bodyDark){
      document.body.classList.remove('dark-mode');
    } else {
      document.body.classList.add('dark-mode');
    };
  };
</script>

</body>
</html>

templates/sidebar.html
{% load static %}
<nav class="mt-2">
  <ul
    class="nav nav-pills nav-sidebar flex-column"
    data-widget="treeview"
    role="menu"
    data-accordion="false"
  >
    <!-- Add icons to the links using the .nav-icon class
         with font-awesome or any other icon font library -->
    <li class="nav-item">
      <a href="#" class="nav-link">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
          Overview
          <span class="right badge badge-info">Coming Soon</span>
        </p>
      </a>
    </li>
    <li class="nav-header">USAGES</li>
    <li class="nav-item">
      <a href="#" class="nav-link">
        <i class="nav-icon fas fa-chart-area"></i>
        <p>Statistics</p>
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'radius:usages-view' %}" class="nav-link">
        <i class="nav-icon fas fa-money-bill"></i>
        <p>Accounting</p>
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'radius:log-auth-view' %}" class="nav-link">
        <i class="nav-icon fas fa-file"></i>
        <p>Authentication</p>
      </a>
    </li>
    <li class="nav-header">SETTINGS</li>
    <li class="nav-item">
      <a href="#" class="nav-link">
        <i class="nav-icon fas fa-user"></i>
        <p>My Profile</p>
      </a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link">
        <i class="nav-icon fas fa-edit"></i>
        <p>Change Password</p>
      </a>
    </li>
    <li class="nav-header">ADMIN AREA</li>
    <li class="nav-item menu-open">
      <a href="#" class="nav-link">
        <!-- add active -->
        <i class="nav-icon fas fa-users"></i>
        <p>
          Management
          <i class="right fas fa-angle-left"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <!-- add active here -->
            <i class="far fa-circle nav-icon"></i>
            <p>Active User</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Usage Summary</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Search User</p>
          </a>
        </li>
      </ul>
    </li>
  </ul>
</nav>